name: Build ServerArk

on:
  push:
    tags:
      - 'v*'   # läuft nur wenn du ein Tag wie v1.0.0 pushst

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y build-essential libpcap-dev

      - name: Build
        run: make
